stages:
  - init
  - build
  - test
  - finish

.deps:
  before_script:
    - cat schutzbot/team_ssh_keys.txt | tee -a ~/.ssh/authorized_keys > /dev/null
    - curl -LJO https://raw.githubusercontent.com/osbuild/osbuild-composer/main/Schutzfile
    - sudo dnf update -y && sudo dnf install -y podman
  variables:
    RUNNER: aws/fedora-35-x86_64
    INTERNAL_NETWORK: "true"
    QUAY_IO_CONTAINER_URL: quay.io/cloudexperience/cloud-image-val-test
  tags:
    - terraform

.tests:
  extends: .deps
  after_script:
    - schutzbot/update_github_status.sh update || true
    - echo https://redhat.gitlab.io/-/services/products/image-builder/ci/cloud-image-val-ci/-/jobs/${CI_JOB_ID}/artifacts/report.html
  artifacts:
    paths:
      - report.html
    when: always

init:
  stage: init
  script:
    - schutzbot/update_github_status.sh start

container:
  extends: .deps
  stage: build
  script:
    - sudo podman build -t "${QUAY_IO_CONTAINER_URL}":"${CI_COMMIT_REF_SLUG}" .
    - sudo podman push --creds ${QUAY_USERNAME}:${QUAY_PASSWORD} "${QUAY_IO_CONTAINER_URL}":"${CI_COMMIT_REF_SLUG}"

aws:
  stage: test
  extends: .tests
  script:
    - sudo podman pull --creds ${QUAY_USERNAME}:${QUAY_PASSWORD} "${QUAY_IO_CONTAINER_URL}":"${CI_COMMIT_REF_SLUG}"
    - |
      sudo podman run \
      -a stdout -a stderr \
      -e AWS_ACCESS_KEY_ID="${V2_AWS_ACCESS_KEY_ID}" \
      -e AWS_SECRET_ACCESS_KEY="${V2_AWS_SECRET_ACCESS_KEY}" \
      -e AWS_REGION="${AWS_REGION}" \
      -v ./:/tmp:Z \
      "${QUAY_IO_CONTAINER_URL}":"${CI_COMMIT_REF_SLUG}" \
      python cloud-image-val.py -r cloud/sample/resources_aws_marketplace.json -d -p -o /tmp/report.xml

azure:
  stage: test
  extends: .tests
  script:
    - sudo podman pull --creds ${QUAY_USERNAME}:${QUAY_PASSWORD} "${QUAY_IO_CONTAINER_URL}":"${CI_COMMIT_REF_SLUG}"
    - |
      sudo podman run \
      -a stdout -a stderr \
      -e ARM_CLIENT_ID="${V2_AZURE_CLIENT_ID}" \
      -e ARM_CLIENT_SECRET="${V2_AZURE_CLIENT_SECRET}" \
      -e ARM_SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID}" \
      -e ARM_TENANT_ID="${AZURE_TENANT_ID}" \
      -v ./:/tmp:Z \
      "${QUAY_IO_CONTAINER_URL}":"${CI_COMMIT_REF_SLUG}" \
      python cloud-image-val.py -r cloud/sample/resources_azure_marketplace.json -d -p -o /tmp/report.xml

.rhel_runners: &rhel_runners
    RUNNER:
      - aws/centos-stream-8-x86_64
      - aws/rhel-8.4-ga-x86_64
      - aws/rhel-8.6-ga-x86_64
      - aws/rhel-9.0-ga-x86_64
      - aws/rhel-8.7-nightly-x86_64
      - aws/rhel-9.1-nightly-x86_64
      - aws/centos-stream-9-x86_64
    INTERNAL_NETWORK: ["true"]

.fedora_runners: &fedora_runners
    RUNNER:
      - aws/fedora-35-x86_64
      - aws/fedora-36-x86_64

.ib_tests:
  extends: .tests
  after_script:
    - !reference [.tests, after_script]
    - cp /tmp/report.html ./report.html
  parallel:
    matrix:
      - *fedora_runners
      - *rhel_runners

ib-aws:
  stage: test
  extends: .ib_tests
  script:
    - schutzbot/deploy.sh
    - ARTIFACTS=/tmp/ bash /usr/libexec/tests/osbuild-composer/aws.sh

container_main:
  extends: .deps
  stage: finish
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
  script:
    - sudo podman pull --creds ${QUAY_USERNAME}:${QUAY_PASSWORD} "${QUAY_IO_CONTAINER_URL}":main
    - sudo podman tag "${QUAY_IO_CONTAINER_URL}":main "${QUAY_IO_CONTAINER_URL}":latest
    - sudo podman push --creds ${QUAY_USERNAME}:${QUAY_PASSWORD} "${QUAY_IO_CONTAINER_URL}":latest
finish:
  stage: finish
  script:
    - schutzbot/update_github_status.sh finish
