stages:
  - init
  - test
  - finish

.deps:
  image: python:3.8
  before_script:
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - bash get-docker.sh
    - systemctl start docker
    - docker pull quay.io/cloudexperience/cloud-image-val-test:latest 

.tests:
  extends: .deps
  after_script:
    - schutzbot/update_github_status.sh update || true
    - echo https://redhat.gitlab.io/-/services/products/image-builder/ci/cloud-image-val-ci/-/jobs/${CI_JOB_ID}/artifacts/report.html
  artifacts:
    paths:
      - report.html
    when: always

init:
  stage: init
  script:
    - schutzbot/update_github_status.sh start

aws:
  stage: test
  extends: .tests
  script:
    - docker run -a stdout -a stderr -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} quay.io/cloudexperience/cloud-image-val-test:latest python cloud-image-val.py -r cloud/sample/resources_aws.json -d -p -m 'not pub' -o report.xml
  
azure:
  stage: test
  extends: .tests
  script: 
    - docker run -a stdout -a stderr -e ARM_CLIENT_ID=${AZURE_CLIENT_ID} -e ARM_CLIENT_SECRET=${AZURE_CLIENT_SECRET} -e ARM_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID} -e ARM_TENANT_ID=${AZURE_TENANT_ID} quay.io/cloudexperience/cloud-image-val-test:latest python cloud-image-val.py -r cloud/sample/resources_azure.json -d -p -m 'not pub' -o report.xml

  
finish:
  stage: finish
  script:
    - schutzbot/update_github_status.sh finish
